target 'ios' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
end

target 'CucumberTests' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'cucumbertest', :path => '../cucumber'
end
