target 'CucumberTests' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'Cucumberish'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = Gem::Version.new('9.0')
    end
  end
end